name: Update Currency Prices

on:
  schedule:
    - cron: '0 0 * * *'  # هذا يعني أن السكربت سيعمل يوميًا في منتصف الليل (00:00 UTC)
  workflow_dispatch:  # يمكن أيضًا تشغيله يدويًا من GitHub Actions
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # تحديد نسخة Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: |
          python script.py  # تشغيل السكربت الذي ستضعه في المستودع
          
      - name: Upload log file (optional)
        uses: actions/upload-artifact@v2
        with:
          name: log-file
          path: log.txt  # رفع ملف السجل في حال رغبتك في الوصول إليه
